---
title: "Shopping"
author: "John S Butler"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## GENERATE DATA

You can also embed plots, for example:

```{r pressure, echo=FALSE}

N<-1000

Age<-round(runif(N,20,70),digits = 2)
gender_index<-runif(N,0,1)
loyal_index<-runif(N,0,1)
Height<-rep(170,N)

Loyalty<-rep("Yes",N)
loyal_index<-loyal_index>=0.7
Loyalty[loyal_index]="No"
Numerical_Loyalty<-rep(1,N)
Numerical_Loyalty[loyal_index]=0

MacBeth<-rep("Yes",N)
FamilySize<-1+rpois(N,2)


macbeth_index<-runif(N,0,1)
MacBeth[macbeth_index<0.8]="No"
Numerical_MacBeth<-rep(1,N)
Numerical_MacBeth[MacBeth=="No"]=0


Sex<-rep("M",N)

Sex[gender_index>=0.5]="F"
length(Sex=="F")
Numerical_Sex<-rep(1,N)
Numerical_Sex[gender_index>=0.5]=0


Height[gender_index>=0.5]=round(rnorm(sum(gender_index>=0.5),163,5),digits=2)
Height[gender_index<0.5]=round(rnorm(sum(gender_index<0.5),175,7),digits=2)

Spend<-round(20+Age*0.2+20*runif(N,0,1)*Numerical_MacBeth+(runif(N,0,1)-0.5)*Height/200+20*Numerical_Loyalty+10*FamilySize+runif(N,0,40),digits=2)

Data=data.frame(Spend,Age,Sex,Height,Loyalty,FamilySize,MacBeth)


write.csv(Data,file=paste("Shopping.csv", sep = ""))


```

```{r}

summary(Data)

SpendAge = lm(Spend ~ Age,  data = Data) 

summary(SpendAge) 

 SpendMacBeth = lm(Spend~Age+MacBeth,data=Data)
 summary(SpendMacBeth)
 
 
SpendAll<-lm(Spend~Age+MacBeth+Loyalty+Sex+Height+factor(FamilySize),data=Data)
summary(SpendAll)
SpendAll<-lm(Spend~.,data=Data)
summary(SpendAll)
```

```{r}

plot(Spend ~ Age,  data = Data) 

plot(Spend~MacBeth,data=Data)
plot(Spend~Height,data=Data)

```