---
title: "Sexton"
author: "John S Butler"
output:
  pdf_document: default
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## GENERATE DATA


```{r pressure, echo=FALSE}

N<-100

Age<-round(runif(N,20,33),digits = 2)
Distance<-runif(N,10,60)
Angle<-rnorm(N,0,15)


Location<-rep("Home",N)
location_index<-runif(N,0,1)
Location[location_index<0.5]="Away"


eta<-0.05*runif(N,0,1)*Age-0.1*runif(N,0,1)*Distance-0.5*runif(N,0,1)*Angle*Angle
eta<-0.01*Age-0.2*(Distance-25)-0.01*Angle*Angle/10+rnorm(N,mean = 0,0.5)+3
P<-exp(eta)/(1+exp(eta))
Conversion<-rep(0,N)
Conversion[P>0.5]=1
Data=data.frame(Conversion,Age,Distance,Angle,Location)


write.csv(Data,file=paste("Sexton.csv", sep = ""))


```

```{r}

summary(Data)

Sexton = glm(Conversion ~ Distance,  data = Data,family=binomial("logit")) 
summary(Sexton)


```

```{r}


library(ggplot2)
ggplot(Data, aes(x=Distance, y=Conversion)) + geom_point() + 
  stat_smooth(method="glm", method.args=list(family="binomial"), se=FALSE)+xlab("Distance (m)")+ylab("Pr(Conversion)")+ theme(plot.title = element_text(hjust=1.0))+geom_vline(xintercept=50,col="black",size=1,linetype="dotted")+  geom_text(aes(x=53, label="Half Way Line", y=0.5),angle=90)+
  geom_vline(xintercept=0,col="black",size=1,linetype="dotted")+  geom_text(aes(x=3, label="Goal Line", y=0.5),angle=90)
# ggsave("Sexton.png",dpi=300, width = 4, height = 2.5)


```

